name: Continuous Integration WorkFlow
on: 
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
            name: projeto.zip
            path: |
              **.py
              README.md