name: Continuous Integration WorkFlow
on: 
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
            name: projeto.zip
            path: |
              '**.py'
              README.md
  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projeto.zip
      - name: Display structure of downloaded files
        run: ls -R
